version: "3.7"
services:
  db:
    image: postgres:15
    container_name: fsp_service_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fsp_service
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db
